config/routes.rb
Rails.application.routes.draw do
  root   'staticpages#home'
  get    '/projects',    to: 'staticpages#works'
  get    '/publication',    to: 'staticpages#publication'
  get    '/contact',    to: 'staticpages#contact'
  get 'staticpages/works'
  get 'staticpages/publication'
  get 'staticpages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end

  def works
  end

  def publication
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = 'Paiable'
        if page_title.empty?
          base_title
        else
          page_title + ' | ' + base_title
        end
      end
    
      def namer(page_name = '')
        page_name unless page_name.empty?
      end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="container">© 2020 Audrey-Ella-xo</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <div class="namer"><%= namer(yield(:name)) %></div>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside>
    <div class = "intro">
    <%=link_to image_tag("welcome_cats.svg", alt: "Welcome message"), root_path %>    
        <p>I am a fullstack developer</p>
    </div>
    <div class="links">
        <ul>
            <li><%= link_to "Work", projects_path %></li>
            <li><%= link_to "Articles", publication_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>
    </div>
    <div class="socials">
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-medium"></i></a>
        <a href="#"><i class="fas fa-envelope"></i></a>
        <a href="#"><i class="fab fa-skype"></i></a>
    </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/sidebar' %>
    <%= render 'layouts/header' %>
  
    <main class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/staticpages/contact.html.erb
<h1>Staticpages#contact</h1>
<p>Find me in app/views/staticpages/contact.html.erb</p>

app/views/staticpages/home.html.erb
<% provide(:title, "Projects") %>

<section class="about">
<% provide(:name, "Grouped Projects") %>
    <h1>
        <%=image_tag("undraw_software_engineer_lvl5.png", alt: "Welcome message", class: "title-icon")%>
        About me
    </h1>

    <div class="personal-info">
        <h2>Hello, I am Audrey</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, vel!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nemo quo sed aliquid nam adipisci reprehenderit commodi ipsam? Accusantium doloribus voluptate, ad deleniti quo impedit reiciendis nihil officiis minus temporibus.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente nesciunt illum iusto ad a cum?</p>
    </div>
</section>

app/views/staticpages/publication.html.erb
<section class="publication">
            <h1>
                <%=image_tag("undraw_online_information_4ui6.svg", alt: "...", class: "title-icon")%>
                Articles
            </h1>

            <div class="card mb-3">
                <div class="row no-gutters">
                  <div class="col-md-4">
                  <%=image_tag("visual-heirarchy.jpg", alt: "...", class: "card-img img-responsive")%>
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">Best Way to Make Your Design Communicate</h5>
                      <p class="card-text"><small class="text-muted">Nov 30, 2019</small></p>
                      <p class="card-text">Visual hierarchy is one of the most important principles behind effective web design. I say this because the goal...</p>
                      <div class="full-article">
                          <a href="#">READ THE FULL ARTICLE</a>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        </section>

app/views/staticpages/works.html.erb
<section class="featured-works">
            <h1>
                <img class="title-icon" src="./assets/images/Portfolio tinified pictures/portfolio svg/undraw_dev_focus_b9xo.svg" alt="">
                Featured Works
            </h1>
            
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                        <div class="project">
                        <%=link_to image_tag("mockup-of-a-macbook-pro-on-a-coffee-shop-table-2315-el1.png", alt: "Welcome message", class: "img-responsive d-block w-100" ), "#" %>    

                            <div class="detail"> 
                                <p>This is a wider card with supporting text below as a natural lead-in to additional content</p>
                                  <div>
                                      <a href="#"><i class="fas fa-eye"></i></a>
                                      <a href="#"><i class="fas fa-code"></i></a>
                                  </div>
                            </div>
                        </div>
                  </div>
                  <div class="carousel-item">
                    <div class="project">
                    <%=link_to image_tag("mockup-of-a-macbook-pro-placed-on-a-white-work-desk-next-to-some-plant-pots-495-el.png", alt: "Welcome message", class: "img-responsive d-block w-100" ), "#" %> 
                            <div class="detail"> 
                                <p>This is a wider card with supporting text below as a natural lead-in to additional content</p>
                                  <div>
                                      <a href="#"><i class="fas fa-eye"></i></a>
                                      <a href="#"><i class="fas fa-code"></i></a>
                                  </div>
                            </div>
                        </div>
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
        </section>